name: Build

on:
  push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run tests
      uses: sbt/setup-sbt@v1
      with:
        sbt-runner-version: 1.11.5
    - run: sbt "test-only tests.CITests"
