name: Build

on:
  push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install metafacture-fix 1.2.0
      run: |
        git clone https://github.com/metafacture/metafacture-fix.git -b 1.2.0
        cd metafacture-fix
        ./gradlew publishToMavenLocal
        cd ..
    - name: Run tests
      run: sbt "test-only tests.CITests"

